### ISSUE TITLE
default_units doesn't seem to be used?

### ISSUE THREAD

**Issue by balvig** [wikiti/open-weather-api-rb#1]
Thanks for creating this great gem!

I was trying out switching the unit to `metric`, but it seems that `default_units` isn't actually considered when building the request? 🤔 

I was going to have a go at forking/fixing, but not sure what would be the best way to test that within the conventions of the current test suite 🙇  If you have any pointers would be great! 🙏

**Comment by wikiti** [comment]
Hi @balvig!

Thanks you for using this gem!

After reviewing the code, it seems that I did not fully implement the `default_units`. [This](https://github.com/wikiti/open-weather-api-rb/blob/master/lib/open-weather-api/resources/base.rb#L59) may be the method that must be edited, adding a new default option:

````rb
def build_params(parameters = {})
  {
    APPID: @api_obj.api_key,
    lang:  @api_obj.default_language,
    units: @api_obj.default_units
  }.merge(parameters)
 end
````

As for testing, I would add the test as a new `describe` or `context` group in [spec/raw_spec.rb](https://github.com/wikiti/open-weather-api-rb/blob/master/spec/raw_spec.rb). Something like this:

````rb
describe'When using default units' do
  context 'When using the default unit' do
    it 'should use the default unit' do
      # ...
    end
  end

  context 'When overriding the default unit' do
    it 'should use the default unit' do
      # ...
    end
  end
end
````

If you don't feel comfortable patching this gem, I can do it for you 😄 


Best regards,
Daniel

**Comment by balvig** [comment]
@wikiti thanks for getting back! 🙏  

Aha, I see. 🤔  

The one thing I'm not clear on is how to perform the assertions that the correct units are being sent, as most of the specs I found seem to only check whether we get back a 200 or not, so wasn't sure where to go from there... 😅  Maybe I overlooked something? 🙇

**Comment by wikiti** [comment]
Hi, @balvig!

I've checked the source code. Gosh, I wrote this gem some time ago. With more ruby experience, and some perspective, I can easily say that this gem is pure garbage: hard to test, hard to keep track of values (requests and responses), hard to mantain...

I think that I'm going to do a rework for this gem. Maybe a new API, more resource classes, CI based, more developments tools (like rubocop), etcetera.

In the meantime, could you please check if the fix on the [`fix-parameters-management`](https://github.com/wikiti/open-weather-api-rb/tree/fix-parameters-management) works for you? If so, I'll release version 0.0.8 for you.

**Comment by balvig** [comment]
> Gosh, I wrote this gem some time ago

Hehe, we’ve all been there...thanks for coming back and addressing this issue in spite of that! 🙏 
The branch indeed seems to do the trick ☀️ 

Thanks again for the help! Much appreciated 🙇
